import {
    ClearSunny,
    MostlyClear,
    Cloudy,
    PartlyCloudy,
    MostlyCloudy,
    Fog,
    FogLight,
    Drizzle,
    Rain,
    RainLight,
    RainHeavy,
    Snow,
    Flurries,
    SnowLight,
    SnowHeavy,
    FreezingRainDrizzle,
    FreezingRain,
    FreezingRainLight,
    FreezingRainHeavy,
    IcePellets,
    IcePelletsHeavy,
    IcePelletsLight,
    LightningStorm,
} from '../assets';

export const WeatherImgs = {
    
        "1000": ClearSunny,
        "1100": MostlyClear,
        "1001": Cloudy,
        "1101": PartlyCloudy,
        "1102": MostlyCloudy,
        "2000": Fog,
        "2100": FogLight,
        "4000": Drizzle,
        "4001": Rain,   
        "4200": RainLight,
        "4201": RainHeavy,
        "5000": Snow,
        "5001": Flurries,
        "5100": SnowLight,
        "5101": SnowHeavy,
        "6000": FreezingRainDrizzle,
        "6001": FreezingRain,
        "6200": FreezingRainLight,
        "6201": FreezingRainHeavy,
        "7000": IcePellets,
        "7101": IcePelletsHeavy,
        "7102": IcePelletsLight,
        "8000": LightningStorm,
};